# CMake generated Testfile for 
# Source directory: /Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples
# Build directory: /Users/celinesantosh/Desktop/sem_5/wasmtime_dev
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(anyref-c "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/wasmtime-anyref")
set_tests_properties(anyref-c PROPERTIES  WORKING_DIRECTORY "../.." _BACKTRACE_TRIPLES "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;28;add_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;46;create_target;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;0;")
add_test(async-c "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/wasmtime-async")
set_tests_properties(async-c PROPERTIES  WORKING_DIRECTORY "../.." _BACKTRACE_TRIPLES "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;28;add_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;47;create_target;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;0;")
add_test(externref-c "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/wasmtime-externref")
set_tests_properties(externref-c PROPERTIES  WORKING_DIRECTORY "../.." _BACKTRACE_TRIPLES "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;28;add_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;48;create_target;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;0;")
add_test(fib-debug-c "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/wasmtime-fib-debug")
set_tests_properties(fib-debug-c PROPERTIES  WORKING_DIRECTORY "../.." _BACKTRACE_TRIPLES "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;28;add_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;49;create_target;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;0;")
add_test(fuel-c "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/wasmtime-fuel")
set_tests_properties(fuel-c PROPERTIES  WORKING_DIRECTORY "../.." _BACKTRACE_TRIPLES "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;28;add_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;50;create_target;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;0;")
add_test(gcd-c "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/wasmtime-gcd")
set_tests_properties(gcd-c PROPERTIES  WORKING_DIRECTORY "../.." _BACKTRACE_TRIPLES "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;28;add_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;51;create_target;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;0;")
add_test(hello-c "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/wasmtime-hello")
set_tests_properties(hello-c PROPERTIES  WORKING_DIRECTORY "../.." _BACKTRACE_TRIPLES "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;28;add_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;52;create_target;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;0;")
add_test(interrupt-c "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/wasmtime-interrupt")
set_tests_properties(interrupt-c PROPERTIES  WORKING_DIRECTORY "../.." _BACKTRACE_TRIPLES "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;28;add_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;53;create_target;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;0;")
add_test(linking-c "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/wasmtime-linking")
set_tests_properties(linking-c PROPERTIES  WORKING_DIRECTORY "../.." _BACKTRACE_TRIPLES "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;28;add_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;54;create_target;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;0;")
add_test(memory-c "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/wasmtime-memory")
set_tests_properties(memory-c PROPERTIES  WORKING_DIRECTORY "../.." _BACKTRACE_TRIPLES "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;28;add_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;55;create_target;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;0;")
add_test(multi-c "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/wasmtime-multi")
set_tests_properties(multi-c PROPERTIES  WORKING_DIRECTORY "../.." _BACKTRACE_TRIPLES "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;28;add_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;56;create_target;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;0;")
add_test(multimemory-c "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/wasmtime-multimemory")
set_tests_properties(multimemory-c PROPERTIES  WORKING_DIRECTORY "../.." _BACKTRACE_TRIPLES "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;28;add_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;57;create_target;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;0;")
add_test(serialize-c "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/wasmtime-serialize")
set_tests_properties(serialize-c PROPERTIES  WORKING_DIRECTORY "../.." _BACKTRACE_TRIPLES "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;28;add_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;58;create_target;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;0;")
add_test(threads-c "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/wasmtime-threads")
set_tests_properties(threads-c PROPERTIES  WORKING_DIRECTORY "../.." _BACKTRACE_TRIPLES "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;28;add_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;59;create_target;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;0;")
add_test(wasi-c "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/wasmtime-wasi")
set_tests_properties(wasi-c PROPERTIES  WORKING_DIRECTORY "../.." _BACKTRACE_TRIPLES "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;28;add_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;60;create_target;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;0;")
add_test(anyref-rust "cargo" "run" "--example" "anyref")
set_tests_properties(anyref-rust PROPERTIES  WORKING_DIRECTORY "../.." _BACKTRACE_TRIPLES "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;35;add_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;63;create_rust_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;0;")
add_test(epochs-rust "cargo" "run" "--example" "epochs")
set_tests_properties(epochs-rust PROPERTIES  WORKING_DIRECTORY "../.." _BACKTRACE_TRIPLES "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;35;add_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;68;create_rust_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;0;")
add_test(externref-rust "cargo" "run" "--example" "externref")
set_tests_properties(externref-rust PROPERTIES  WORKING_DIRECTORY "../.." _BACKTRACE_TRIPLES "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;35;add_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;69;create_rust_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;0;")
add_test(fib-debug-rust "cargo" "run" "--example" "fib-debug")
set_tests_properties(fib-debug-rust PROPERTIES  WORKING_DIRECTORY "../.." _BACKTRACE_TRIPLES "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;35;add_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;70;create_rust_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;0;")
add_test(fuel-rust "cargo" "run" "--example" "fuel")
set_tests_properties(fuel-rust PROPERTIES  WORKING_DIRECTORY "../.." _BACKTRACE_TRIPLES "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;35;add_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;71;create_rust_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;0;")
add_test(gcd-rust "cargo" "run" "--example" "gcd")
set_tests_properties(gcd-rust PROPERTIES  WORKING_DIRECTORY "../.." _BACKTRACE_TRIPLES "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;35;add_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;72;create_rust_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;0;")
add_test(hello-rust "cargo" "run" "--example" "hello")
set_tests_properties(hello-rust PROPERTIES  WORKING_DIRECTORY "../.." _BACKTRACE_TRIPLES "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;35;add_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;73;create_rust_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;0;")
add_test(interrupt-rust "cargo" "run" "--example" "interrupt")
set_tests_properties(interrupt-rust PROPERTIES  WORKING_DIRECTORY "../.." _BACKTRACE_TRIPLES "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;35;add_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;74;create_rust_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;0;")
add_test(linking-rust "cargo" "run" "--example" "linking")
set_tests_properties(linking-rust PROPERTIES  WORKING_DIRECTORY "../.." _BACKTRACE_TRIPLES "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;35;add_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;75;create_rust_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;0;")
add_test(memory-rust "cargo" "run" "--example" "memory")
set_tests_properties(memory-rust PROPERTIES  WORKING_DIRECTORY "../.." _BACKTRACE_TRIPLES "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;35;add_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;76;create_rust_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;0;")
add_test(multi-rust "cargo" "run" "--example" "multi")
set_tests_properties(multi-rust PROPERTIES  WORKING_DIRECTORY "../.." _BACKTRACE_TRIPLES "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;35;add_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;77;create_rust_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;0;")
add_test(multimemory-rust "cargo" "run" "--example" "multimemory")
set_tests_properties(multimemory-rust PROPERTIES  WORKING_DIRECTORY "../.." _BACKTRACE_TRIPLES "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;35;add_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;78;create_rust_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;0;")
add_test(serialize-rust "cargo" "run" "--example" "serialize")
set_tests_properties(serialize-rust PROPERTIES  WORKING_DIRECTORY "../.." _BACKTRACE_TRIPLES "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;35;add_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;79;create_rust_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;0;")
add_test(threads-rust "cargo" "run" "--example" "threads")
set_tests_properties(threads-rust PROPERTIES  WORKING_DIRECTORY "../.." _BACKTRACE_TRIPLES "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;35;add_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;80;create_rust_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;0;")
add_test(wasi-rust "cargo" "run" "--example" "wasi")
set_tests_properties(wasi-rust PROPERTIES  WORKING_DIRECTORY "../.." _BACKTRACE_TRIPLES "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;35;add_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;81;create_rust_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;0;")
add_test(tokio-rust "cargo" "run" "--example" "tokio" "--features" "wasi-common/tokio")
set_tests_properties(tokio-rust PROPERTIES  WORKING_DIRECTORY "../.." _BACKTRACE_TRIPLES "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;33;add_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;82;create_rust_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;0;")
add_test(component-rust "cargo" "run" "--example" "component")
set_tests_properties(component-rust PROPERTIES  WORKING_DIRECTORY "../.." _BACKTRACE_TRIPLES "/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;35;add_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;83;create_rust_test;/Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples/CMakeLists.txt;0;")
subdirs("wasmtime")
