# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.29.6/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.29.6/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/celinesantosh/Desktop/sem_5/wasmtime_dev/examples

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/celinesantosh/Desktop/sem_5/wasmtime_dev

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/Cellar/cmake/3.29.6/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.29.6/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.29.6/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.29.6/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.29.6/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.29.6/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.29.6/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.29.6/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.29.6/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/celinesantosh/Desktop/sem_5/wasmtime_dev/CMakeFiles /Users/celinesantosh/Desktop/sem_5/wasmtime_dev//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/celinesantosh/Desktop/sem_5/wasmtime_dev/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named wasmtime-anyref

# Build rule for target.
wasmtime-anyref: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wasmtime-anyref
.PHONY : wasmtime-anyref

# fast build rule for target.
wasmtime-anyref/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-anyref.dir/build.make CMakeFiles/wasmtime-anyref.dir/build
.PHONY : wasmtime-anyref/fast

#=============================================================================
# Target rules for targets named wasmtime-async

# Build rule for target.
wasmtime-async: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wasmtime-async
.PHONY : wasmtime-async

# fast build rule for target.
wasmtime-async/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-async.dir/build.make CMakeFiles/wasmtime-async.dir/build
.PHONY : wasmtime-async/fast

#=============================================================================
# Target rules for targets named wasmtime-externref

# Build rule for target.
wasmtime-externref: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wasmtime-externref
.PHONY : wasmtime-externref

# fast build rule for target.
wasmtime-externref/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-externref.dir/build.make CMakeFiles/wasmtime-externref.dir/build
.PHONY : wasmtime-externref/fast

#=============================================================================
# Target rules for targets named wasmtime-fib-debug

# Build rule for target.
wasmtime-fib-debug: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wasmtime-fib-debug
.PHONY : wasmtime-fib-debug

# fast build rule for target.
wasmtime-fib-debug/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-fib-debug.dir/build.make CMakeFiles/wasmtime-fib-debug.dir/build
.PHONY : wasmtime-fib-debug/fast

#=============================================================================
# Target rules for targets named wasmtime-fuel

# Build rule for target.
wasmtime-fuel: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wasmtime-fuel
.PHONY : wasmtime-fuel

# fast build rule for target.
wasmtime-fuel/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-fuel.dir/build.make CMakeFiles/wasmtime-fuel.dir/build
.PHONY : wasmtime-fuel/fast

#=============================================================================
# Target rules for targets named wasmtime-gcd

# Build rule for target.
wasmtime-gcd: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wasmtime-gcd
.PHONY : wasmtime-gcd

# fast build rule for target.
wasmtime-gcd/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-gcd.dir/build.make CMakeFiles/wasmtime-gcd.dir/build
.PHONY : wasmtime-gcd/fast

#=============================================================================
# Target rules for targets named wasmtime-hello

# Build rule for target.
wasmtime-hello: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wasmtime-hello
.PHONY : wasmtime-hello

# fast build rule for target.
wasmtime-hello/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-hello.dir/build.make CMakeFiles/wasmtime-hello.dir/build
.PHONY : wasmtime-hello/fast

#=============================================================================
# Target rules for targets named wasmtime-interrupt

# Build rule for target.
wasmtime-interrupt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wasmtime-interrupt
.PHONY : wasmtime-interrupt

# fast build rule for target.
wasmtime-interrupt/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-interrupt.dir/build.make CMakeFiles/wasmtime-interrupt.dir/build
.PHONY : wasmtime-interrupt/fast

#=============================================================================
# Target rules for targets named wasmtime-linking

# Build rule for target.
wasmtime-linking: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wasmtime-linking
.PHONY : wasmtime-linking

# fast build rule for target.
wasmtime-linking/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-linking.dir/build.make CMakeFiles/wasmtime-linking.dir/build
.PHONY : wasmtime-linking/fast

#=============================================================================
# Target rules for targets named wasmtime-memory

# Build rule for target.
wasmtime-memory: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wasmtime-memory
.PHONY : wasmtime-memory

# fast build rule for target.
wasmtime-memory/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-memory.dir/build.make CMakeFiles/wasmtime-memory.dir/build
.PHONY : wasmtime-memory/fast

#=============================================================================
# Target rules for targets named wasmtime-multi

# Build rule for target.
wasmtime-multi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wasmtime-multi
.PHONY : wasmtime-multi

# fast build rule for target.
wasmtime-multi/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-multi.dir/build.make CMakeFiles/wasmtime-multi.dir/build
.PHONY : wasmtime-multi/fast

#=============================================================================
# Target rules for targets named wasmtime-multimemory

# Build rule for target.
wasmtime-multimemory: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wasmtime-multimemory
.PHONY : wasmtime-multimemory

# fast build rule for target.
wasmtime-multimemory/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-multimemory.dir/build.make CMakeFiles/wasmtime-multimemory.dir/build
.PHONY : wasmtime-multimemory/fast

#=============================================================================
# Target rules for targets named wasmtime-serialize

# Build rule for target.
wasmtime-serialize: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wasmtime-serialize
.PHONY : wasmtime-serialize

# fast build rule for target.
wasmtime-serialize/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-serialize.dir/build.make CMakeFiles/wasmtime-serialize.dir/build
.PHONY : wasmtime-serialize/fast

#=============================================================================
# Target rules for targets named wasmtime-threads

# Build rule for target.
wasmtime-threads: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wasmtime-threads
.PHONY : wasmtime-threads

# fast build rule for target.
wasmtime-threads/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-threads.dir/build.make CMakeFiles/wasmtime-threads.dir/build
.PHONY : wasmtime-threads/fast

#=============================================================================
# Target rules for targets named wasmtime-wasi

# Build rule for target.
wasmtime-wasi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wasmtime-wasi
.PHONY : wasmtime-wasi

# fast build rule for target.
wasmtime-wasi/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-wasi.dir/build.make CMakeFiles/wasmtime-wasi.dir/build
.PHONY : wasmtime-wasi/fast

#=============================================================================
# Target rules for targets named wasmtime-crate

# Build rule for target.
wasmtime-crate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wasmtime-crate
.PHONY : wasmtime-crate

# fast build rule for target.
wasmtime-crate/fast:
	$(MAKE) $(MAKESILENT) -f wasmtime/CMakeFiles/wasmtime-crate.dir/build.make wasmtime/CMakeFiles/wasmtime-crate.dir/build
.PHONY : wasmtime-crate/fast

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) $(MAKESILENT) -f wasmtime/CMakeFiles/doc.dir/build.make wasmtime/CMakeFiles/doc.dir/build
.PHONY : doc/fast

anyref.o: anyref.c.o
.PHONY : anyref.o

# target to build an object file
anyref.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-anyref.dir/build.make CMakeFiles/wasmtime-anyref.dir/anyref.c.o
.PHONY : anyref.c.o

anyref.i: anyref.c.i
.PHONY : anyref.i

# target to preprocess a source file
anyref.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-anyref.dir/build.make CMakeFiles/wasmtime-anyref.dir/anyref.c.i
.PHONY : anyref.c.i

anyref.s: anyref.c.s
.PHONY : anyref.s

# target to generate assembly for a file
anyref.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-anyref.dir/build.make CMakeFiles/wasmtime-anyref.dir/anyref.c.s
.PHONY : anyref.c.s

async.o: async.cpp.o
.PHONY : async.o

# target to build an object file
async.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-async.dir/build.make CMakeFiles/wasmtime-async.dir/async.cpp.o
.PHONY : async.cpp.o

async.i: async.cpp.i
.PHONY : async.i

# target to preprocess a source file
async.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-async.dir/build.make CMakeFiles/wasmtime-async.dir/async.cpp.i
.PHONY : async.cpp.i

async.s: async.cpp.s
.PHONY : async.s

# target to generate assembly for a file
async.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-async.dir/build.make CMakeFiles/wasmtime-async.dir/async.cpp.s
.PHONY : async.cpp.s

externref.o: externref.c.o
.PHONY : externref.o

# target to build an object file
externref.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-externref.dir/build.make CMakeFiles/wasmtime-externref.dir/externref.c.o
.PHONY : externref.c.o

externref.i: externref.c.i
.PHONY : externref.i

# target to preprocess a source file
externref.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-externref.dir/build.make CMakeFiles/wasmtime-externref.dir/externref.c.i
.PHONY : externref.c.i

externref.s: externref.c.s
.PHONY : externref.s

# target to generate assembly for a file
externref.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-externref.dir/build.make CMakeFiles/wasmtime-externref.dir/externref.c.s
.PHONY : externref.c.s

fib-debug/main.o: fib-debug/main.c.o
.PHONY : fib-debug/main.o

# target to build an object file
fib-debug/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-fib-debug.dir/build.make CMakeFiles/wasmtime-fib-debug.dir/fib-debug/main.c.o
.PHONY : fib-debug/main.c.o

fib-debug/main.i: fib-debug/main.c.i
.PHONY : fib-debug/main.i

# target to preprocess a source file
fib-debug/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-fib-debug.dir/build.make CMakeFiles/wasmtime-fib-debug.dir/fib-debug/main.c.i
.PHONY : fib-debug/main.c.i

fib-debug/main.s: fib-debug/main.c.s
.PHONY : fib-debug/main.s

# target to generate assembly for a file
fib-debug/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-fib-debug.dir/build.make CMakeFiles/wasmtime-fib-debug.dir/fib-debug/main.c.s
.PHONY : fib-debug/main.c.s

fuel.o: fuel.c.o
.PHONY : fuel.o

# target to build an object file
fuel.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-fuel.dir/build.make CMakeFiles/wasmtime-fuel.dir/fuel.c.o
.PHONY : fuel.c.o

fuel.i: fuel.c.i
.PHONY : fuel.i

# target to preprocess a source file
fuel.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-fuel.dir/build.make CMakeFiles/wasmtime-fuel.dir/fuel.c.i
.PHONY : fuel.c.i

fuel.s: fuel.c.s
.PHONY : fuel.s

# target to generate assembly for a file
fuel.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-fuel.dir/build.make CMakeFiles/wasmtime-fuel.dir/fuel.c.s
.PHONY : fuel.c.s

gcd.o: gcd.c.o
.PHONY : gcd.o

# target to build an object file
gcd.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-gcd.dir/build.make CMakeFiles/wasmtime-gcd.dir/gcd.c.o
.PHONY : gcd.c.o

gcd.i: gcd.c.i
.PHONY : gcd.i

# target to preprocess a source file
gcd.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-gcd.dir/build.make CMakeFiles/wasmtime-gcd.dir/gcd.c.i
.PHONY : gcd.c.i

gcd.s: gcd.c.s
.PHONY : gcd.s

# target to generate assembly for a file
gcd.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-gcd.dir/build.make CMakeFiles/wasmtime-gcd.dir/gcd.c.s
.PHONY : gcd.c.s

hello.o: hello.c.o
.PHONY : hello.o

# target to build an object file
hello.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-hello.dir/build.make CMakeFiles/wasmtime-hello.dir/hello.c.o
.PHONY : hello.c.o

hello.i: hello.c.i
.PHONY : hello.i

# target to preprocess a source file
hello.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-hello.dir/build.make CMakeFiles/wasmtime-hello.dir/hello.c.i
.PHONY : hello.c.i

hello.s: hello.c.s
.PHONY : hello.s

# target to generate assembly for a file
hello.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-hello.dir/build.make CMakeFiles/wasmtime-hello.dir/hello.c.s
.PHONY : hello.c.s

interrupt.o: interrupt.c.o
.PHONY : interrupt.o

# target to build an object file
interrupt.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-interrupt.dir/build.make CMakeFiles/wasmtime-interrupt.dir/interrupt.c.o
.PHONY : interrupt.c.o

interrupt.i: interrupt.c.i
.PHONY : interrupt.i

# target to preprocess a source file
interrupt.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-interrupt.dir/build.make CMakeFiles/wasmtime-interrupt.dir/interrupt.c.i
.PHONY : interrupt.c.i

interrupt.s: interrupt.c.s
.PHONY : interrupt.s

# target to generate assembly for a file
interrupt.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-interrupt.dir/build.make CMakeFiles/wasmtime-interrupt.dir/interrupt.c.s
.PHONY : interrupt.c.s

linking.o: linking.c.o
.PHONY : linking.o

# target to build an object file
linking.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-linking.dir/build.make CMakeFiles/wasmtime-linking.dir/linking.c.o
.PHONY : linking.c.o

linking.i: linking.c.i
.PHONY : linking.i

# target to preprocess a source file
linking.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-linking.dir/build.make CMakeFiles/wasmtime-linking.dir/linking.c.i
.PHONY : linking.c.i

linking.s: linking.c.s
.PHONY : linking.s

# target to generate assembly for a file
linking.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-linking.dir/build.make CMakeFiles/wasmtime-linking.dir/linking.c.s
.PHONY : linking.c.s

memory.o: memory.c.o
.PHONY : memory.o

# target to build an object file
memory.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-memory.dir/build.make CMakeFiles/wasmtime-memory.dir/memory.c.o
.PHONY : memory.c.o

memory.i: memory.c.i
.PHONY : memory.i

# target to preprocess a source file
memory.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-memory.dir/build.make CMakeFiles/wasmtime-memory.dir/memory.c.i
.PHONY : memory.c.i

memory.s: memory.c.s
.PHONY : memory.s

# target to generate assembly for a file
memory.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-memory.dir/build.make CMakeFiles/wasmtime-memory.dir/memory.c.s
.PHONY : memory.c.s

multi.o: multi.c.o
.PHONY : multi.o

# target to build an object file
multi.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-multi.dir/build.make CMakeFiles/wasmtime-multi.dir/multi.c.o
.PHONY : multi.c.o

multi.i: multi.c.i
.PHONY : multi.i

# target to preprocess a source file
multi.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-multi.dir/build.make CMakeFiles/wasmtime-multi.dir/multi.c.i
.PHONY : multi.c.i

multi.s: multi.c.s
.PHONY : multi.s

# target to generate assembly for a file
multi.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-multi.dir/build.make CMakeFiles/wasmtime-multi.dir/multi.c.s
.PHONY : multi.c.s

multimemory.o: multimemory.c.o
.PHONY : multimemory.o

# target to build an object file
multimemory.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-multimemory.dir/build.make CMakeFiles/wasmtime-multimemory.dir/multimemory.c.o
.PHONY : multimemory.c.o

multimemory.i: multimemory.c.i
.PHONY : multimemory.i

# target to preprocess a source file
multimemory.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-multimemory.dir/build.make CMakeFiles/wasmtime-multimemory.dir/multimemory.c.i
.PHONY : multimemory.c.i

multimemory.s: multimemory.c.s
.PHONY : multimemory.s

# target to generate assembly for a file
multimemory.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-multimemory.dir/build.make CMakeFiles/wasmtime-multimemory.dir/multimemory.c.s
.PHONY : multimemory.c.s

serialize.o: serialize.c.o
.PHONY : serialize.o

# target to build an object file
serialize.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-serialize.dir/build.make CMakeFiles/wasmtime-serialize.dir/serialize.c.o
.PHONY : serialize.c.o

serialize.i: serialize.c.i
.PHONY : serialize.i

# target to preprocess a source file
serialize.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-serialize.dir/build.make CMakeFiles/wasmtime-serialize.dir/serialize.c.i
.PHONY : serialize.c.i

serialize.s: serialize.c.s
.PHONY : serialize.s

# target to generate assembly for a file
serialize.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-serialize.dir/build.make CMakeFiles/wasmtime-serialize.dir/serialize.c.s
.PHONY : serialize.c.s

threads.o: threads.c.o
.PHONY : threads.o

# target to build an object file
threads.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-threads.dir/build.make CMakeFiles/wasmtime-threads.dir/threads.c.o
.PHONY : threads.c.o

threads.i: threads.c.i
.PHONY : threads.i

# target to preprocess a source file
threads.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-threads.dir/build.make CMakeFiles/wasmtime-threads.dir/threads.c.i
.PHONY : threads.c.i

threads.s: threads.c.s
.PHONY : threads.s

# target to generate assembly for a file
threads.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-threads.dir/build.make CMakeFiles/wasmtime-threads.dir/threads.c.s
.PHONY : threads.c.s

wasi/main.o: wasi/main.c.o
.PHONY : wasi/main.o

# target to build an object file
wasi/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-wasi.dir/build.make CMakeFiles/wasmtime-wasi.dir/wasi/main.c.o
.PHONY : wasi/main.c.o

wasi/main.i: wasi/main.c.i
.PHONY : wasi/main.i

# target to preprocess a source file
wasi/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-wasi.dir/build.make CMakeFiles/wasmtime-wasi.dir/wasi/main.c.i
.PHONY : wasi/main.c.i

wasi/main.s: wasi/main.c.s
.PHONY : wasi/main.s

# target to generate assembly for a file
wasi/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wasmtime-wasi.dir/build.make CMakeFiles/wasmtime-wasi.dir/wasi/main.c.s
.PHONY : wasi/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... doc"
	@echo "... wasmtime-crate"
	@echo "... wasmtime-anyref"
	@echo "... wasmtime-async"
	@echo "... wasmtime-externref"
	@echo "... wasmtime-fib-debug"
	@echo "... wasmtime-fuel"
	@echo "... wasmtime-gcd"
	@echo "... wasmtime-hello"
	@echo "... wasmtime-interrupt"
	@echo "... wasmtime-linking"
	@echo "... wasmtime-memory"
	@echo "... wasmtime-multi"
	@echo "... wasmtime-multimemory"
	@echo "... wasmtime-serialize"
	@echo "... wasmtime-threads"
	@echo "... wasmtime-wasi"
	@echo "... anyref.o"
	@echo "... anyref.i"
	@echo "... anyref.s"
	@echo "... async.o"
	@echo "... async.i"
	@echo "... async.s"
	@echo "... externref.o"
	@echo "... externref.i"
	@echo "... externref.s"
	@echo "... fib-debug/main.o"
	@echo "... fib-debug/main.i"
	@echo "... fib-debug/main.s"
	@echo "... fuel.o"
	@echo "... fuel.i"
	@echo "... fuel.s"
	@echo "... gcd.o"
	@echo "... gcd.i"
	@echo "... gcd.s"
	@echo "... hello.o"
	@echo "... hello.i"
	@echo "... hello.s"
	@echo "... interrupt.o"
	@echo "... interrupt.i"
	@echo "... interrupt.s"
	@echo "... linking.o"
	@echo "... linking.i"
	@echo "... linking.s"
	@echo "... memory.o"
	@echo "... memory.i"
	@echo "... memory.s"
	@echo "... multi.o"
	@echo "... multi.i"
	@echo "... multi.s"
	@echo "... multimemory.o"
	@echo "... multimemory.i"
	@echo "... multimemory.s"
	@echo "... serialize.o"
	@echo "... serialize.i"
	@echo "... serialize.s"
	@echo "... threads.o"
	@echo "... threads.i"
	@echo "... threads.s"
	@echo "... wasi/main.o"
	@echo "... wasi/main.i"
	@echo "... wasi/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

